### ISSUE TITLE
Android Studio showing error and not opening in Ubuntu

### ISSUE THREAD

**Issue by tango4567** [tango4567/solutions#22]
Recently I am facing following error after deleting AndroidStudio cache for the new updates.

```
Internal error. Please refer to https://code.google.com/p/android/issues

java.lang.NoSuchMethodError: com.intellij.ide.plugins.PluginManagerCore.loadDescriptors()[Lcom/intellij/ide/plugins/IdeaPluginDescriptorImpl;
at com.a.a.b.b.ar.a(ar.java:121)
at com.a.a.b.b.ar.a(ar.java:71)
at com.intellij.idea.MainImpl.start(MainImpl.java:19)
at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:303)
at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
at java.lang.Thread.run(Thread.java:748)

-----
JRE 1.8.0_242-release-1644-b3-6222593 amd64 by JetBrains s.r.o
/snap/android-studio/94/android-studio/jre/jre"
```

**Comment by tango4567** [comment]
Simply I grab last two of error msg and googled it.
**Solution** 👉 `sudo rm -rf ~/.local/share/Google/AndroidStudio4.1/marketplace/lib`
**Explanation** 👉 It's happening because of Markdown lib
**Source** 👉 [StackOver](https://stackoverflow.com/a/64338900) 👈 
**About Android Studio** 👇

```
Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-42-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: com.thoughtworks.gauge
Current Desktop: ubuntu:GNOME
```
