### ISSUE TITLE
How to Configure SSL Certificate in Android App

### ISSUE THREAD

**Issue by tango4567** [tango4567/solutions#27]
These are few lists of error/issues while configuring SSL Certificate in Android App. 

1. IOException: Unable to parse TLS packet header
2. `java.security.cert.CertificateException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE`
3. After adding SSL certificate why request time is increased for getting response.

**Comment by tango4567** [comment]
Another output while using using https.
<details>     


```
2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err: java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:170)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.parsing.JsonParser.makeHttpRequest(JsonParser.java:44)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.async.LoginAsync.doInBackground(LoginAsync.java:39)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.async.LoginAsync.doInBackground(LoginAsync.java:18)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
        2021-05-17 19:04:36.141 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at java.lang.Thread.run(Thread.java:923)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at libcore.io.Linux.android_getaddrinfo(Native Method)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
        2021-05-17 19:04:36.142 8471-8507/tarunmahajan.com W/System.err: 	... 18 more
        2021-05-17 19:04:36.143 8471-8507/tarunmahajan.com W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.getBoolean(java.lang.String)' on a null object reference
        2021-05-17 19:04:36.143 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.async.LoginAsync.doInBackground(LoginAsync.java:40)
        2021-05-17 19:04:36.143 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.async.LoginAsync.doInBackground(LoginAsync.java:18)
        2021-05-17 19:04:36.143 8471-8507/tarunmahajan.com W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
        2021-05-17 19:04:36.143 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        2021-05-17 19:04:36.143 8471-8507/tarunmahajan.com W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        2021-05-17 19:04:36.144 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        2021-05-17 19:04:36.144 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        2021-05-17 19:04:36.144 8471-8507/tarunmahajan.com W/System.err:     at java.lang.Thread.run(Thread.java:923)
        2021-05-17 19:04:36.145 8471-8471/tarunmahajan.com D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10153; state: ENABLED
        2021-05-17 19:04:36.150 8471-8525/tarunmahajan.com W/System.err: java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname
        2021-05-17 19:04:36.150 8471-8525/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:170)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.parsing.JsonParser.makeHttpRequest(JsonParser.java:44)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.async.ValidationAsync.doInBackground(ValidationAsync.java:36)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.async.ValidationAsync.doInBackground(ValidationAsync.java:17)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        2021-05-17 19:04:36.151 8471-8525/tarunmahajan.com W/System.err:     at java.lang.Thread.run(Thread.java:923)
        2021-05-17 19:04:36.152 8471-8525/tarunmahajan.com W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.getBoolean(java.lang.String)' on a null object reference
        2021-05-17 19:04:36.152 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.async.ValidationAsync.doInBackground(ValidationAsync.java:37)
        2021-05-17 19:04:36.153 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.async.ValidationAsync.doInBackground(ValidationAsync.java:17)
        2021-05-17 19:04:36.153 8471-8525/tarunmahajan.com W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
        2021-05-17 19:04:36.153 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        2021-05-17 19:04:36.153 8471-8525/tarunmahajan.com W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        2021-05-17 19:04:36.153 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        2021-05-17 19:04:36.153 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        2021-05-17 19:04:36.153 8471-8525/tarunmahajan.com W/System.err:     at java.lang.Thread.run(Thread.java:923)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err: java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:170)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
        2021-05-17 19:04:36.157 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
        2021-05-17 19:04:36.158 8471-8507/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
        2021-05-17 19:04:36.158 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.parsing.JsonParser.makeHttpRequest(JsonParser.java:44)
        2021-05-17 19:04:36.158 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.async.ValidationAsync.doInBackground(ValidationAsync.java:36)
        2021-05-17 19:04:36.158 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.async.ValidationAsync.doInBackground(ValidationAsync.java:17)
        2021-05-17 19:04:36.158 8471-8507/tarunmahajan.com W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
        2021-05-17 19:04:36.158 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        2021-05-17 19:04:36.158 8471-8507/tarunmahajan.com W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        2021-05-17 19:04:36.160 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        2021-05-17 19:04:36.160 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        2021-05-17 19:04:36.160 8471-8507/tarunmahajan.com W/System.err:     at java.lang.Thread.run(Thread.java:923)
        2021-05-17 19:04:36.161 8471-8507/tarunmahajan.com W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.getBoolean(java.lang.String)' on a null object reference
        2021-05-17 19:04:36.161 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.async.ValidationAsync.doInBackground(ValidationAsync.java:37)
        2021-05-17 19:04:36.162 8471-8507/tarunmahajan.com W/System.err:     at com.stufeed.async.ValidationAsync.doInBackground(ValidationAsync.java:17)
        2021-05-17 19:04:36.162 8471-8507/tarunmahajan.com W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
        2021-05-17 19:04:36.162 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        2021-05-17 19:04:36.162 8471-8507/tarunmahajan.com W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        2021-05-17 19:04:36.162 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        2021-05-17 19:04:36.162 8471-8507/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        2021-05-17 19:04:36.162 8471-8507/tarunmahajan.com W/System.err:     at java.lang.Thread.run(Thread.java:923)
        2021-05-17 19:04:36.187 8471-8525/tarunmahajan.com W/System.err: java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname
        2021-05-17 19:04:36.187 8471-8525/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
        2021-05-17 19:04:36.187 8471-8525/tarunmahajan.com W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        2021-05-17 19:04:36.187 8471-8525/tarunmahajan.com W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        2021-05-17 19:04:36.187 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
        2021-05-17 19:04:36.187 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:170)
        2021-05-17 19:04:36.187 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
        2021-05-17 19:04:36.190 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
        2021-05-17 19:04:36.190 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
        2021-05-17 19:04:36.191 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
        2021-05-17 19:04:36.191 8471-8525/tarunmahajan.com W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
        2021-05-17 19:04:36.192 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.parsing.JsonParser.makeHttpRequest(JsonParser.java:44)
        2021-05-17 19:04:36.192 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.async.RegisterAsync.doInBackground(RegisterAsync.java:47)
        2021-05-17 19:04:36.192 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.async.RegisterAsync.doInBackground(RegisterAsync.java:20)
        2021-05-17 19:04:36.193 8471-8525/tarunmahajan.com W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
        2021-05-17 19:04:36.193 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        2021-05-17 19:04:36.193 8471-8525/tarunmahajan.com W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        2021-05-17 19:04:36.194 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        2021-05-17 19:04:36.194 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        2021-05-17 19:04:36.194 8471-8525/tarunmahajan.com W/System.err:     at java.lang.Thread.run(Thread.java:923)
        2021-05-17 19:04:36.195 8471-8525/tarunmahajan.com W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.getBoolean(java.lang.String)' on a null object reference
        2021-05-17 19:04:36.196 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.async.RegisterAsync.doInBackground(RegisterAsync.java:48)
        2021-05-17 19:04:36.196 8471-8525/tarunmahajan.com W/System.err:     at com.stufeed.async.RegisterAsync.doInBackground(RegisterAsync.java:20)
        2021-05-17 19:04:36.196 8471-8525/tarunmahajan.com W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
        2021-05-17 19:04:36.197 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        2021-05-17 19:04:36.197 8471-8525/tarunmahajan.com W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        2021-05-17 19:04:36.197 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        2021-05-17 19:04:36.197 8471-8525/tarunmahajan.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        2021-05-17 19:04:36.197 8471-8525/tarunmahajan.com W/System.err:     at java.lang.Thread.run(Thread.java:923)
```

</details>
Off Topic: [How to create collapsible section containing code]()

**Comment by tango4567** [comment]
I found temporary solutions [StackOverFlow](https://stackoverflow.com/questions/8169999/how-can-i-create-a-self-signed-cert-for-localhost/48790088#48790088)
