### ISSUE TITLE
NoReverseMatch Error on Django Redirect

### ISSUE THREAD

**Issue by tango4567** [tango4567/solutions#43]
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">NoReverseMatch at /register</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Reverse for 'register' not found. 'register' is not a valid view function or pattern name.</pre>

Request Method: | POST
-- | --
http://127.0.0.1:8000/register
4.1
NoReverseMatch
Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
C:\Users\TarunMahajan\.virtualenvs\pracPy-b7vdO4P5\lib\site-packages\django\urls\resolvers.py, line 803, in _reverse_with_prefix
website.views.register
C:\Users\TarunMahajan\.virtualenvs\pracPy-b7vdO4P5\Scripts\python.exe
3.10.4
['C:\\Users\\TarunMahajan\\djangoProjects\\pracPy',  'C:\\Python310\\python310.zip',  'C:\\Python310\\DLLs',  'C:\\Python310\\lib',  'C:\\Python310',  'C:\\Users\\TarunMahajan\\.virtualenvs\\pracPy-b7vdO4P5',  'C:\\Users\\TarunMahajan\\.virtualenvs\\pracPy-b7vdO4P5\\lib\\site-packages']
Mon, 22 Aug 2022 01:45:33 +0000

</body>
</html>

<details>
<summary>Log</summary>

Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/register

Django Version: 4.1
Python Version: 3.10.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'website']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "C:\Users\TarunMahajan\\.virtualenvs\pracPy-b7vdO4P5\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TarunMahajan\\.virtualenvs\pracPy-b7vdO4P5\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TarunMahajan\\djangoProjects\pracPy\website\views.py", line 83, in register
    return redirect('register')
  File "C:\Users\TarunMahajan\\.virtualenvs\pracPy-b7vdO4P5\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\TarunMahajan\\.virtualenvs\pracPy-b7vdO4P5\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\TarunMahajan\\.virtualenvs\pracPy-b7vdO4P5\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\TarunMahajan\\.virtualenvs\pracPy-b7vdO4P5\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /register
Exception Value: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
</details>

Here we can see **register** function is registered  
Using the URLconf defined in tarunmahajan.urls, Django tried these URL patterns, in this order:

1. admin/
2. 
3. old
4. about
5. hello
6. register

**Comment by tango4567** [comment]
Well I used ` return render(request, 'register.html')` instead of `return redirect('register')` so it's solved my problem temporary but I'm keep looking on it. Even after registering function properly in urls.py

Some interesting conversation I found mention below.
1. [NoReverseMatch error](https://forum.djangoproject.com/t/noreversematch-error/11232/39)
2. [NoReverseMatch at /blog/redirect2](https://stackoverflow.com/questions/71819596/noreversematch-at-blog-redirect2)
3. [Why am I getting no reverse match error in django 3.2?](https://stackoverflow.com/questions/69454553/why-am-i-getting-no-reverse-match-error-in-django-3-2)
